### ISSUE TITLE
What is the steam api key entry in settings.json for?

### ISSUE THREAD

**Issue by The-personified-devil** [PazerOP/tf2_bot_detector#103]
It gives access to the steam api ... duh
My real question is as following: What features use the steam api (bot detection etc.)?
Thanks

**Comment by PazerOP** [comment]
The only thing it does right now is compare a player's ingame name against their steam community name. If there is a mismatch, displays them on the scoreboard as "<ingame name> (<steamcommunity name>)" with the steamcommunity name in red. The reason it's not an advertised feature or exposed anywhere is because I wanted to add a few more features + a guide for how to set it up first.
