### ISSUE TITLE
[Enhancement/Tweak] Increase delay between failed votes OR assume re-vote chance

### ISSUE THREAD

**Issue by CrazyGunman2C4U** [PazerOP/tf2_bot_detector#154]
There is a cooldown between failed and successful votes. 

Since we don't know if a vote was successful, I'd suggest to either increase the delay between votes a good bit (30-45 sec?, 60 sec?) or 'assume' if the vote is failing or not.

![vote](https://user-images.githubusercontent.com/53367662/87825891-38a21b00-c878-11ea-9793-cdb9110497e7.png)

If a vote keeps failing (like 3 times in a row), delay the following votes until a sane result can be exprected (after a minute, on vote target switch, etc).

**Comment by CrazyGunman2C4U** [comment]
Edit: "If a vote keeps failing (like 3 times in a row)"

As in, if we keep initiating votes. Thus not having to "read" any additional game date as the program itself should know when it **tries** to initiate a vote.

**Comment by The-personified-devil** [comment]
The bot creators use the vote sounds to find out if votes are being called. We could also use this. And if we take it to far we could make a screenshot and somehow read the vote caller and vote target.

**Comment by CrazyGunman2C4U** [comment]
That could take it a bit too far. While recording sounds (or is it possible to read played sounds using developer 1?), taking screenshots and analyzing them shouldn't trigger VAC in any way as it doesn't interact with the game, actually analyzing it is probably out of the scope of this project. Imaging having to find the proper text with all these different voting boxes (custom huds).

**Comment by PazerOP** [comment]
It's actually simpler than that, and if you compile a debug build you'll see messages like 

* `UserMessageType::CallVoteFailed`
* `UserMessageType::VoteFailed`
* `UserMessageType::VotePass`
* `UserMessageType::VoteSetup`
* `UserMessageType::VoteStart`

in the chat log. For whatever reason, valve decided to give each vote update its own usermessage type, and those are visible to us in the console log if we have net_showmessage set to svc_UserMessage: 
```
Msg from <ip>: svc_UserMessage: type <usermessage type #>, bytes <size, not really useful>
```

I just haven't taken any action based on these messages yet because I wanted to wait until after 1.1 was released.

Trying to use OCR to read the voting box is largely impossible due to the infinite customizability of HUDs.

**Comment by ClusterConsultant** [comment]
issue moved to #168
