### ISSUE TITLE
[Bug] Votekicks being deemed as "not possible" when they are

### ISSUE THREAD

**Issue by AyeTSG** [PazerOP/tf2_bot_detector#177]
I've noticed that whenever a player using TF2BD joins a match and a votekick is requested by TF2BD the tool will fail to start the votekick for a good 5-15 seconds after joining the match. It says this is because 0% of friendly players are connected, but this happens even when having a full team.

**Comment by CrazyGunman2C4U** [comment]
That was added to make sure the vote doesn't fail, because team mates are still joining. When they've chosen a class they could see the vote window, but iirc couldn't vote.

![grafik](https://user-images.githubusercontent.com/53367662/89683202-67039b00-d8f8-11ea-9292-e6019b6991dc.png)

Set Autp votekick delay to 0 in the settings to disable the new behavior.

**Comment by AyeTSG** [comment]
Ah, I see. My bad, I believed this was a bug.
