### ISSUE TITLE
add rule for new bots. Milenko.neocities.net, THE GREAT MILENKO, Milenko anti-bot, Anything with MILENKO in it.

### ISSUE THREAD

**Issue by ShaneDawsonsCat** [PazerOP/tf2_bot_detector#200]
Milenko is a supposed "anti bot" bot hoster, but these bots recently have gone rogue, undercover as "fake" milenko bots. this "milenko" group has gone a month or so undetected as a normal bot host, and is even making money off donations from unsuspecting people, who do not know that their money is going towards bad bots, and not good bots. 

Salam Alaykum.

**Comment by ClusterConsultant** [comment]
Someone on the discord made some regex for this.

**Comment by incontestableness** [comment]
Milenko here. That's pretty funny OP, considering you were trying to spam my discord yesterday, starting with that same phrase you mention at the end there.

**Comment by incontestableness** [comment]
![Screenshot_2020-08-25_09-26-53](https://user-images.githubusercontent.com/66852150/91186982-45a2fd00-e6b5-11ea-857b-61c216b42dec.png)
:thinking:

**Comment by CrazyGunman2C4U** [comment]
This is just Fornitelad. 

@incontestableness 
Anyway, since you already have a guide explaining how to differentiate your bot from the malicious rest, how about using random names, so we can simply name-ban Milenko and you won't get impersonated.

It's probably also a good idea to change your chat messages from time-to-time.

You could even equip an objector with a ([non-color](https://steamcommunity.com/sharedfiles/filedetails/?id=1772162651&searchtext=Full-Colour) [filtered](https://steamcommunity.com/sharedfiles/filedetails/?id=281434937&searchtext=Full-Colour)) decal which clarifies you are peaceful. Sure, bots could copy that, but they can't use their primary weapon while holding the objector ;)

![BOLD](https://user-images.githubusercontent.com/53367662/91191579-3fcd0c00-e6f5-11ea-8b38-27ab48f85831.png)

**Comment by incontestableness** [comment]
@CrazyGunman2C4U random names would be doable, but I'd have to come up with a bunch of names, which isn't easy. it's also very possible that malicious bot hosters could just fetch all the names in use and then use them themselves, which would make it pointless.

there's only so many variations of a sentence; I'd run out of ideas fast.

an objector would only be on premium bots, which don't need it since they can call votes and use chat.

I already have a fairly complete list of all the malicious bots my milenko bots have seen running the past few days - there's 205 at the moment. I've found it to be very accurate in my testing. [you can download it here](https://incontestableness.github.io/milenko/playerlist.milenko-list.json), but I'm still waiting on PazerOP to decide to put it in the wiki. the list is curated by automatically detecting malicious bots via signals they send as well as my own name list -- this means it doesn't necessarily require a list of player names to detect bots; as such, malicious bots impersonating milenko are still detected. if everyone were to use this list as well, I feel like that might be more effective.

**Comment by CrazyGunman2C4U** [comment]
I joined your Discord server and will reply there from now on to keep this on-topic.

Thanks for the quick reply.

**Comment by poohook** [comment]
> 
> 
> This is just Fornitelad.
> 
> @incontestableness
> Anyway, since you already have a guide explaining how to differentiate your bot from the malicious rest, how about using random names, so we can simply name-ban Milenko and you won't get impersonated.
> 
> It's probably also a good idea to change your chat messages from time-to-time.
> 
> You could even equip an objector with a ([non-color](https://steamcommunity.com/sharedfiles/filedetails/?id=1772162651) [filtered](https://steamcommunity.com/sharedfiles/filedetails/?id=281434937)) decal which clarifies you are peaceful. Sure, bots could copy that, but they can't use their primary weapon while holding the objector ;)
> 
> ![BOLD](https://user-images.githubusercontent.com/53367662/91191579-3fcd0c00-e6f5-11ea-8b38-27ab48f85831.png)

so bots are OK now? nice thanks

**Comment by cyberkitsune** [comment]
Why doesn't @incontestableness just share all the steam id's of the legit bot killers with us for a "whitelist?"

**Comment by The-personified-devil** [comment]
I think it's because that would make the bad bots be able to target his bots (Or at least a lot easier to.).

**Comment by 107zxz** [comment]
All bots are bad bots. I don't see the point of having 4 player slots of any server taken up by bots and "anti-bots". It's a stupid idea that adds to the problem, and is the exact opposite approach to the bot detector in solving it.

I hope that this project adds no official support for "anti-bots", as it would oppose the purpose of the bot detector itself.

**Comment by incontestableness** [comment]
The bots leave automatically after about 15 seconds. They don't take up player slots; Valve wrote a very efficient lobby system for TF2. Milenko bots joining and then leaving matches are a non-issue because available players will be assigned to the match after bots leave. Any further issues regarding Milenko bots should be taken to the discord server, here: [https://discord.gg/UsZM3Kw](https://discord.gg/UsZM3Kw)

**Comment by ClusterConsultant** [comment]
This project does not advocate for the usage of these "antibots." That being said our efforts are focused on more overtly malicious bots. I am going to close this for now and if it becomes problematic in the future it will be either reopened or a fresh issue made.
