### ISSUE TITLE
Add a button to check if user is in any cheater list.

### ISSUE THREAD

**Issue by douglasb2310** [PazerOP/tf2_bot_detector#220]
It'd be useful for contributing to unofficial lists.

I know many players who've been cheating on Team Fortress 2 (such as U:1:393195043), but I don't know if they're listed by any lists and I haven't seen them in a while.

**Comment by Kenajcrap** [comment]
You can already see who is marked on the lists you added (or created) locally (see https://github.com/PazerOP/tf2_bot_detector/wiki/Customization). If you mean for the program to check for, and update, cheaters on a centralized way, that is intentionally not possible because it could be easily abused by bad actors.
