### ISSUE TITLE
"client stuck on object 0/" message while playing

### ISSUE THREAD

**Issue by tariqmudallal** [PazerOP/tf2_bot_detector#221]
![image](https://user-images.githubusercontent.com/9893082/97351355-de3d3100-184e-11eb-80a1-05deadba32ca.png)

As you see in the image, I get the aforementioned error on the top right when I play casual with TF2BD open every time I get into a Casual game.

**Comment by ClusterConsultant** [comment]
Please upload your debug report.
From what I know, this particular error is related to community maps (and some spots on poorly made official maps). Are you actually experiencing stuck behavior? It does not make sense to me that tf2bd would be causing this since it doesn't do anything to map geography.

**Comment by ClusterConsultant** [comment]
I'm going to go ahead and close this since there have been no further reports and I am nearly certain this is unrelated to TF2BD
