### ISSUE TITLE
[BUG] Shadowplay does not work when using Bot Detector

### ISSUE THREAD

**Issue by JitterDev** [PazerOP/tf2_bot_detector#231]
**Describe the bug**
Cannot use ShadowPlay while using Bot Detector.

**To Reproduce**
Run Bot Detector
Try to save video of TF2 with Shadowplay
Will not look right

**Expected behavior**

**Logs**
Add any relevant logs. Logs are found by going to File → Open Logs Folder

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10, 8, 7]
 - Version [e.g. 1.1.0.674]
Windows 10 Pro
Build 19041.630
Version 2004, But the last time I used Bot Detector (Stopped using it because of this) Was probably around version 1904.

**Additional context**
I do not have any footage of this right now, but I will get some soon after publishing this.

**Comment by ClusterConsultant** [comment]
After some quick testing we were unable to reproduce. Which version of bot detector are you on? I can't think of any way that it would interfere with shadow play

**Comment by JitterDev** [comment]
> After some quick testing we were unable to reproduce. Which version of bot detector are you on? I can't think of any way that it would interfere with shadow play

It could be something else, I don't know. I'll send some videos and screenshots on it after my classes are over for the day, which will be in around 3ish hours.
As for your question, I'm currently on the latest version of Bot Detector, v1.1.0.674

**Comment by JitterDev** [comment]
@ClusterConsultant 
Since I cannot attach MP4 files to GitHub, here's a Discord link which will download what happens when I try to use Shadowplay.
[Link](https://cdn.discordapp.com/attachments/711357131688902719/783761652783906847/2020-12-02_12-25-13.mp4)

**Comment by moebkun** [comment]
This seems to be more of an Shadowplay issue choosing the wrong window to record, I would suggest you to use the replay buffer feature of OBS rather than shadowplay or if you're adamant on using shadowplay you could try to set up desktop capture under privacy control https://i.imgur.com/kRF1SZo.png, that way it should record what you see, not a specific program

**Comment by ClusterConsultant** [comment]
After some investigation this does seem to be an issue with ShadowPlay rather than TF2BD. I am unable to reproduce with my own ShadowPlay but I can find pleanty of other people complaining about ShadowPlay not recording the correct thing on various forums. I can also recommend the replay buffer feature of OBS if ShadowPlay is too buggy.
