### ISSUE TITLE
Investigate unnecessary vcredist invocations/UAC prompts

### ISSUE THREAD

**Issue by PazerOP** [PazerOP/tf2_bot_detector#264]
Apparently for some, the vcredist step is running every single time there is an update, and even requesting UAC in some (all?) cases. I haven't experienced this in my testing, but perhaps that is because I have a dev toolchain installed.

**Comment by Kenajcrap** [comment]
It might bring up a UAC prompt only if the person has set UAC to "always" instead of the default "only when apps try to make changes to my computer". It might be worth investigating if that's the case.
[How to change UAC level](https://www.tenforums.com/tutorials/3577-change-user-account-control-uac-settings-windows-10-a.html)
