### ISSUE TITLE
Custom Name Submission

### ISSUE THREAD

**Issue by Bruhmaster43** [PazerOP/tf2_bot_detector#294]
It's a bit of a pain when some bots aren't detected as they are using less common names and not spamming line breakers etc. So I believe an easy to use name addition system would be handy. 

Maybe there could be a system where when two players on a team have the exact same name, call out in team chat that there is a name stealer. Maybe even kick the player with the identical name that connected least recently.

I do not know how hard this would be to implement but it would be incredibly useful for detecting many more cheaters that disguise names to avoid being kicked.

**Comment by Kenajcrap** [comment]
the problem is that the namestealer bots do not use THE SAME name as the target, they insert a invisible, zero width character somewhere in the middle, so that the game doesn't append a `(1)` like it does with normal repeated names.
But banning those characters or removing them before comparing the names is not as simple as it seems due to how Unicode works. There is a good discussion about this at #218

**Comment by thejaviertc** [comment]
@KenajcrapIt's just what you said. Probably a good thing that can be done is to mark automatically as "Suspect" if he has one of the invisible char, because the 80% who use it are bots.

**Comment by ClusterConsultant** [comment]
#218 is the proper place for this conversation.

>So I believe an easy to use name addition system would be handy.
@Bruhmaster43 what exactly do you mean by this?

**Comment by andy013** [comment]
@thejaviertc The app already does this for some zero-width characters that are only used by bots. The problem is they can just change to another character and even use legitimate characters that just don't render in tf2 (at least on the windows version). You can't just flag these players as bots because there might be a real player that has that character in their name. 

There are literally hundreds of thousands of unicode characters so it doesn't make sense to create some sort of blacklist for each one used. There might be a way to filter the name string and compare it to other people to see if it's a bot trying to copy someone but it's not as simple as it sounds.

**Comment by ClusterConsultant** [comment]
This issue will be closed in a few days if this is not updated with further information as I suspect this is asking for something similar to #297
