### ISSUE TITLE
[BUG] Tool tried to auto kick a real player who didn't seem to be cheating

### ISSUE THREAD

**Issue by andy013** [PazerOP/tf2_bot_detector#309]
Tonight while playing, for the first time I encountered a player that is included within the official player ban list that wasn't an automated bot but a real player. He had over 2k hours in TF2 and seemed to just be a good sniper. He might have been cheating, I don't know, but I don't think players like this should be included in the auto kick list. He also had the unicode character \u200f in his name so it's possible he was flagged for this and falsely included in the list.

Even if you have 100% proof this player is cheating, I still think you should just mark real players as suspicious rather than auto kick them. The auto kick should be used only for bots and not real player. The reason I think this is because it is difficult to get other players to vote kick a real player who just seems to be good, especially when they just joined the server. It's pointless to auto kick these players as it will most likely fail so you may as well just mark them as suspicious in the tool and let the user decided when and if to kick them.

**Comment by brachistosaurus** [comment]
1. Some good players cheat. Some players use subtle cheats. Some toggle it on and off.

1. Many human cheaters have already been added to the list (without distinction), so it's implausible, at this point, to remove all of them or to change the tag for all of them.

1. Discussion on adding a separate tag for Human Cheaters: #255 

1. Suspicious players used to be on the Official List, but they were removed. Probably because they weren't confirmed for anything: #174

**Comment by ClusterConsultant** [comment]
This is not a bug. If they are on the official list, they were caught cheating and it is non-negotiable. If they are on a third party list, we do not support those.
