### ISSUE TITLE
Installation dependency issue

### ISSUE THREAD

**Issue by 2l47** [PazerOP/tf2_bot_detector#328]
**Describe the bug**
Trying to manually install by running the msixbundles or using the powershell command fails. Occurs with both the Public and Nightly bundles.

**To Reproduce**
1. Download and install vcredist from https://aka.ms/vs/16/release/vc_redist.x64.exe as per [README](https://github.com/PazerOP/tf2_bot_detector#manualportable-install)
2. Download nightly build from https://tf2bd-util.pazer.us/AppInstaller/Nightly.msixbundle, sourced from the [wiki](https://github.com/PazerOP/tf2_bot_detector/wiki/Installation) app path
3. Run bundle
4. See error `App Installer failed to install package dependencies. Ask the developer for Microsoft.VCLibs.140.00.UWPDesktop package.`

Alternatively, run the powershell command on the wiki for the public bundle. See the same dependency error.

**Desktop (please complete the following information):**
- OS: Windows 10
- Version of bot detector: Public or Nightly

**Comment by 2l47** [comment]
Workaround: download and install the dependency from https://aka.ms/Microsoft.VCLibs.x64.14.00.Desktop.appx

**Comment by ClusterConsultant** [comment]
Even though I think this dependency could be bundled as part of the msixbundle, I am considering this a documentation issue since the power shell installation method is not really supported. That being said, I've updated https://github.com/PazerOP/tf2_bot_detector/wiki/Installation to hopefully be more clear.
