### ISSUE TITLE
Player flashing in purple for no reason [BUG]

### ISSUE THREAD

**Issue by thediscover22450** [PazerOP/tf2_bot_detector#353]
**Describe the bug**
This guy (https://steamcommunity.com/profiles/76561198984740228) was flashing in purple in the tf2 bot detector window for no reason. He was not marked as cheater in any playerlist. I tried to manually mark him as cheater and then remove the mark but it didn't work. I had to disable chat warnings to stop annoying people

**To Reproduce**
1. Join a game with this guy

**Expected behavior**
No flashing, as he's not a cheater and he's not in any playerlist.

**Logs**
https://privatebin.net/?e873f51f2fccf57e#BXYAzufyKJYQBLMxhrMCy3s8kMoHAPciRoeJeCYtXr96

**Screenshots**
![1](https://user-images.githubusercontent.com/40403858/127041104-5b6f72c7-8a05-4dae-b4eb-07e2c42796ce.PNG)

**Desktop (please completeoooooooo the following information):**
> - OS: Windows 10 Home 64 Bits
> - TF2 Bot Detector v1.2.1.934

**Comment by Link2006** [comment]
From checking your logs, the player was using the same trick that bots use to steal names which triggered the rules for "Name stealing bots"; This usually means that they were in fact cheating with a fake name and thus not a bug.

**Comment by ClusterConsultant** [comment]
I am not certain how you determined that since the logs posted are incomplete and don't appear to contain gremlin characters. A gremlin character does exist since we can see it in the screenshot but without the full actual logs I can't determine what rule they are triggering. I can say that account looks to be fairly suspicious and the shown name in the screen shot does not appear in their alias history. Full logs can be uploaded directly to github by just attaching the debug zip to a comment

**Comment by ClusterConsultant** [comment]
Also, you don't need to manually set the rcon settings anymore.

**Comment by meep2k** [comment]
[20:18:54] ModeratorLogic.cpp(187):OnRuleMatch: [TRANSIENT] Marked [U:1:1024474500] with Cheater due to rule match with "Generic name-stealing bot"
