### ISSUE TITLE
Spoofing name on bot detector

### ISSUE THREAD

**Issue by Jesseman1** [PazerOP/tf2_bot_detector#377]
I'm not sure if this is a known thing or something new, but I came across a player cheater who was able to spoof their name multiple times, so their steam profile, their in-game name, and their name on bot detector were all different from each other. The player was aware of how the bot detector worked and mocked it before kicking all the players with his party of bots.

**Comment by Kenajcrap** [comment]
A human cheater not having been picked up by the tool is not out of the normal, since the ways the tool uses to **automatically** mark accounts [are very simple and easy to circumvent](https://github.com/PazerOP/tf2_bot_detector/wiki#how-does-it-work).
As for him "spoofing his name and steam profile", this bug was fixed by valve a few days ago, and should not be possible anymore. 

Either way, the bug did not affect the tool at all, since the means by which it obtains the player's steamID was not affected by the bug at all. That is all to say that if you had right clicked the cheating player and manually marked him as a cheater, the tool would properly warn you about it in future games, just as with any other player.

**Comment by ClusterConsultant** [comment]
Kenajcrap is correct.

**Comment by Jesseman1** [comment]
This was last night it happened. In-game his name was some date, in bot detector his name was "kick the bots", and his steam profile was a random collection of letters and numbers.

**Comment by Kenajcrap** [comment]
then its not what I explained. Could upload the logs from the pertinent day so we can take a look? Make sure to also include the one from the `console` folder.
![image](https://user-images.githubusercontent.com/25385928/136717686-1662ffd4-383e-460f-9635-f63db1983c4c.png)

**Comment by Jesseman1** [comment]
[2021-10-09_22-49-33.log](https://github.com/PazerOP/tf2_bot_detector/files/7326239/2021-10-09_22-49-33.log)
[console_2021-10-09_22-49-33.log](https://github.com/PazerOP/tf2_bot_detector/files/7326241/console_2021-10-09_22-49-33.log)
Here are the logs and console from the other night, the player in question speaks in chat at 01:25:37, and apparently does not have a steam ID.
