### ISSUE TITLE
Votekicked someone who says they weren't a cheater

### ISSUE THREAD

**Issue by ziggythehamster** [PazerOP/tf2_bot_detector#382]
This may not be the correct place to bring this up, so feel free to direct me to the right place.

I encountered a user today who is on the trusted list (https://tf2bdd.pazer.us/v1/steamids) who says they are not a cheater. I, of course, auto votekicked them. If they are in fact not a cheater, they shouldn't be on that list. They were a soldier when I was playing. I didn't see any evidence of cheats, but I see one comment on their profile about being a doubletap cheater from 11/18/2021. They were added to the list a few days after that. The entries on the trusted list don't have the `proof` section filled in (I [fill the proof section in on my list](https://github.com/ziggythehamster/botdetector.tf-lists/blob/main/playerlist.ziggythehamster.json) and had assumed that was standard practice).

This is the entry on the trusted list:

```json
{
    "attributes": [
        "cheater"
    ],
    "last_seen": {
        "player_name": "Runker",
        "time": 1637641032
    },
    "steamid": "[U:1:1230464212]"
},
```

And their profile link is http://steamcommunity.com/profiles/76561199190729940.

Is there any chance that someone remembers why they added them? The player says they got added because they called Pazer a dork, which makes me lean toward them actually being a cheater (they know about this list and the author and their excuse is that Pazer is thin-skinned?), but if they aren't, they shouldn't get marked.

**Comment by Barmem** [comment]
bruh

**Comment by BitmapDummy** [comment]
If they are on the official list then they are guaranteed to have cheated in the past. Obviously these people would say things like that when they see you use the bot detector.

**Comment by ziggythehamster** [comment]
Well, this is the "trusted" list, not the official one, though both seem to be maintained by Pazer. I wasn't sure what the governance is for getting on the list in the first place, and it sounds like this is a deserved ban.

**Comment by Kenajcrap** [comment]
Third party lists such as the list you mentioned are not supported or condoned by the project, [as it is said in the wiki](https://github.com/PazerOP/tf2_bot_detector/wiki/Customization#third-party-player-lists-and-rules). Some considerations:

Cheaters don't cheat all the time.
The trusted list is maintained by a few people pazer trusts enough, cheaters/bots get added to the list if those people encounter them in-game and mark them as such.
Filling in "proof" goes against what this tool is useful for, which is automating a repetitive and boring task so you can have more time to actually enjoy the game, this also applies to the people maintaining the lists. So since there is no proof, the distributed lists mentioned in the wiki are all only useful if you trust their maintainers.
I would advise you not to use a list if you do not know or do not trust their maintainers. This goes for even the official list.
The maintainers for the trusted list can be found by the `@trusted` role in the tool's discord server.

**Comment by ClusterConsultant** [comment]
Nothing more needs to be said on this matter

**Comment by ziggythehamster** [comment]
Yeah, this was clarified in Discord - seems like it's on Pazer's VPS but not actually maintained by them. And also that people aren't added by mistake, so 100% this can be closed. Sorry for wasting your time :).

**Comment by ClusterConsultant** [comment]
It is not a waste of time to ask questions. The next time someone asks something similar I can point at this issue saving time in the future.
