### ISSUE TITLE
Non-ASCII characters displayed as question marks

### ISSUE THREAD

**Issue by lithiumjs** [PazerOP/tf2_bot_detector#78]
Cyrillic letters (and probably other non-ASCII) are displayed in the logs as question marks; most probably a font issue.

Here's a screenshot from the game: 
![image](https://user-images.githubusercontent.com/32413310/84204531-0c92bd80-aab4-11ea-80ec-b434cacbc53a.png)

Compare that to a screenshot from the program: 
![image](https://user-images.githubusercontent.com/32413310/84204566-1e746080-aab4-11ea-8690-1007f3a4924b.png)

**Comment by ClusterConsultant** [comment]
Suspected to be a font issue stemming from ImGui.

**Comment by PazerOP** [comment]
Specifically, I haven't just added all characters, since ImGui is not really intended to be used for user-facing/non-english GUIs. Every single character you could possibly want is rendered into the font page on startup, increasing startup time and memory usage. There is probably room for an on-demand solution that could be pushed up to imgui master.

**Comment by ClusterConsultant** [comment]
Duplicate of #38
