### ISSUE TITLE
add instruction for building from sources

### ISSUE THREAD

**Issue by Xephobia** [PazerOP/tf2_bot_detector#80]
Hello, i wanna help you make an automated build system but i think there is steps i'm missing. Could you give us the builds instructions?

**Comment by ClusterConsultant** [comment]
Cursory guide done. Working on a more complete and user friendly guide

**Comment by PazerOP** [comment]
Cursory guide: https://github.com/PazerOP/tf2_bot_detector/wiki/Compiling

**Comment by bgausden** [comment]
Couple of things I had to work through. Maybe only my environment but maybe relevant to the compile docs:
* I had to install the build tools as I hadn't done any C/C++ dev previously. Probably doesn't affect anyone else. Is there a min version required though?
* In VS Code I modified the discovered kits and created new kits that specify ``toolchainFile="D:/git/vcpkg/scripts/buildsystems/vcpkg.cmake"`` in cmake-tools-kits.json. This ensures the packages installed with vcpkg are visible to VS Code and the compiler. Maybe only necessary if building in VS Code?
* VS Code - Insiders didn't automatically set the include path. I had to invoke via the command palette "C/C++: Edit Configurations (UI)" and configure the ``c_cpp_properties.json`` config file. Once done system includes are found and we can compile.
* CMake couldn't find libzip. I had to copy a cmake script that finds libzip and call the new script from ``CMakeLists.txt``.
* I manually installed the dependencies before I realised there was a batch file to do so. Am I correct though that the batch file presumes vcpkg.exe already exists in the root of the tf2bd project?

**Comment by ClusterConsultant** [comment]
I'm going to put this down as done since if you are compiling you should be able to follow the guide https://github.com/PazerOP/tf2_bot_detector/wiki/Compiling at the very least. Any kind of modification is going to depend on your environment and it would be unreasonable to make a guide for every possible. Bespoke support will be provided on the discord server and if there is a common mistake or question the guide will be updated as necessary,
